### ISSUE TITLE
Simplifying the clone/pull/run instructions

### ISSUE THREAD

**Issue by godbyk** [jalane76/ace-net#7]
A couple notes on your clone/pull/run instructions:

1. Instead of `git clone https://... /path/toace-net/repo`, I'd just write `git clone https://...` as git will automatically create an `ace-net` subdirectory in the current directory to house the repository. Then your next step can just be `cd ace-net` You can skip the environment variable that way.

2. Instead of having them write `chmod +x run-container.sh`, why not set the file permissions on that script and commit it to your container with those permissions? git will make sure they persist on checkout.

**Comment by jalane76** [comment]
1. I still need the environment variable (at the moment) to use in the run script.  But I did simplify the clone command and then set the absolute path to the repo as the env var.
2. I double-checked the permissions on the file and they are set to executable, so good there.
